### ISSUE TITLE
Android app hangs when trying to open shortened Reddit links

### ISSUE THREAD

**Issue by Shished** [QuantumBadger/RedReader#1134] opened 2023-10-02 08:04 UTC
OS: LineageOS 20
Phone: Xiaomi Poco F2 Pro
Redreader version 1.22.

When clicking on shortened Reddit link (reddit.com/r/something/s/randomstring) the app stops responding and can only be swiped out.

Example link: https://reddit.com/r/uktravel/s/qW3nGClxsV

**Comment by nascentt** [comment] 2023-10-06 08:13
Yup this was reported a month ago https://github.com/QuantumBadger/RedReader/issues/1122

It completely breaks the app. Not sure why this isn't being treated with priority.
Now that Relay is subscription only were running out of apps to use whilst RedReader is unusable.

**Comment by QuantumBadger** [comment] 2023-10-06 22:00
> Not sure why this isn't being treated with priority.

The number of people reporting this issue has been relatively low (about 5 people total), and personally I've never run into any of these links. I'd normally do an emergency release if a bug was affecting a large portion of users, like the "permission denied" errors on videos previously.

That's not to say I don't care about this -- I'm planning on merging in the PR this weekend. Before I can do a release there are a handful of other chores to do (e.g. Google won't let me upload a new build until the target SDK version is bumped).

I'll close this as a dupe of #1122, as mentioned the fix will be merged soon.

**Closed by QuantumBadger** 2023-10-06 22:00 UTC
