### ISSUE TITLE
Crash when refreshing on main screen

### ISSUE THREAD

**Issue by afwang** [QuantumBadger/RedReader#516] opened 2017-07-13 15:49 UTC
I found this crash on version 1.9.8.1 installed from the F-droid project.
[redreader_crash_log_f788661d-d4b1-4cb1-9cab-d3be4535d5b3.txt](https://github.com/QuantumBadger/RedReader/files/1145758/redreader_crash_log_f788661d-d4b1-4cb1-9cab-d3be4535d5b3.txt)

Reproduction steps:

1. Launch redreader. The main screen shown should be the one giving an overview of your subscribed subreddits.
2. Tap the refresh button in the app bar.
3. Swipe down while the subscribed subreddits list is refreshing.

I think it might help to reproduce if you're doing this on a slow network. I found it since my network speed is throttled.

**Comment by QuantumBadger** [comment] 2017-07-22 13:34
Thanks for the report. Based on the stack trace, I suspect this is an Android bug.

https://stackoverflow.com/questions/26477660/recyclerview-crashes-when-scrapped-or-attached-views-may-not-be-recycled

Maybe a duplicate of #498.

**Comment by QuantumBadger** [comment] 2021-06-13 12:46
Closing due to lack of activity.

**Closed by QuantumBadger** 2021-06-13 12:46 UTC
Labels: Unconfirmed
