### ISSUE TITLE
Show media as it is buffering

### ISSUE THREAD

**Issue by Kusresa** [QuantumBadger/RedReader#671] opened 2019-05-29 09:00 UTC
Media is only shown when it has fully buffered. This affects user experience when dealing with slower networks or if users just want to see content as it's buffering.

**Comment by lol768** [comment] 2019-06-02 20:10
https://github.com/QuantumBadger/RedReader/issues/659

**Comment by QuantumBadger** [comment] 2020-01-25 17:40
Thanks for the request -- closing as a duplicate of #659

**Closed by QuantumBadger** 2020-01-25 17:40 UTC
Labels: Duplicate
