### ISSUE TITLE
Unexpected Storage Error

### ISSUE THREAD

**Issue by thosoo** [QuantumBadger/RedReader#385] opened 2016-09-11 13:33 UTC
I keep getting an 'Unexpected Storage Error' - even after uninstalling. 
I have still enough free memory, though. 

Phone is Xiaomi Mi4. OS is 6.0.1 (CM13-20160909).

![screenshot_20160911-153502](https://cloud.githubusercontent.com/assets/8445255/18417619/9301f346-7835-11e6-97f1-5cb4725a11fe.png)
`An unknown internal error has occurred, related to the cache storage. You are probably running out of space.`
`Exception: java.io.FileNotFoundException/storage/emulated/0/Android/data/org.quantumbadger.redreader/cache/5db91f67-2bdc-43b7-9437-935d014f1e21.rr_cache_data_tmp: open failed: EACCES (Permission denied)  libcore.io.IoBridge.open(IoBridge.java:452)  java.io.FileOutputStream.<init>(FileOutputStream.java:87)  java.io.FileOutputStream.<init>(FileOutputStream.java:72)  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:203)  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:191)  org.quantumbadger.redreader.cache.CacheManager.openNewCacheFile(CacheManager.java:276)  org.quantumbadger.redreader.cache.CacheDownload$2.onSuccess(CacheDownload.java:160)  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:134)  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:143)  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:90)  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)Caused by: Exception: android.system.ErrnoExceptionopen failed: EACCES (Permission denied)  libcore.io.Posix.open(Native Method)  libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)  libcore.io.IoBridge.open(IoBridge.java:438)  java.io.FileOutputStream.<init>(FileOutputStream.java:87)  java.io.FileOutputStream.<init>(FileOutputStream.java:72)  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:203)  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:191)  org.quantumbadger.redreader.cache.CacheManager.openNewCacheFile(CacheManager.java:276)  org.quantumbadger.redreader.cache.CacheDownload$2.onSuccess(CacheDownload.java:160)  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:134)  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:143)  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:90)  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)`

**Comment by thosoo** [comment] 2016-09-11 13:37
I have still enough free memory, though. 
![screenshot_20160911-153502](https://cloud.githubusercontent.com/assets/8445255/18417619/9301f346-7835-11e6-97f1-5cb4725a11fe.png)

**Comment by QuantumBadger** [comment] 2016-09-11 14:32
Thanks for the report. When did this start occurring? (i.e. straight after an update?) Also, which version of the app are you running?

**Comment by thosoo** [comment] 2016-09-11 15:18
I think it started when RedReader lost its Beta tag. I tried both 1.9.5.1 from FDroid and 1.9.5.2 from Playstore

**Comment by venkateshpitta** [comment] 2018-07-11 01:02
I got it for a few days too.  Version 1.9.8.3 (the most recent from F-Droid store), on Android version 7.0, Motorola G5 Plus.

I got a system alert/warning telling me to clear up some space.  I removed a few folders that were of large size without paying mind to the name of the folders, until there was sufficient free space.  Then upon starting RedReader and trying save image and/or share image, this error kept popping up for a few days.  I have not done anything that I know of to solve this, but the error has stopped occurring all by itself.

What can I do to look deeper into this and work toward fixing this?

**Comment by venkateshpitta** [comment] 2018-07-18 05:01
I got it for a few days too.  Version 1.9.8.3 (the most recent from F-Droid store), on Android version 7.0, Motorola G5 Plus.

I got a system alert/warning telling me to clear up some space.  I removed a few folders that were of large size without paying mind to the name of the folders, until there was sufficient free space.  Then upon starting RedReader and trying save image and/or share image, this error kept popping up for a few days.  I have not done anything that I know of to solve this, but the error has stopped occurring all by itself.

What can I do to look deeper into this and work toward fixing this?

**Comment by QuantumBadger** [comment] 2018-07-31 18:50
> What can I do to look deeper into this and work toward fixing this?

Sorry for the delayed response. This would depend on the exact error message/stack trace. If you see it again, please could you tap the error message and send me the details.

The error in the original report seems to indicate that the system wouldn't allow the app to write a new cache file to disk. If so, I don't think there's much the app can do to recover from this.

**Comment by agibson1083** [comment] 2018-09-11 17:00
Hello, I'm just commenting here because the bug is still open. If this isn't relevant let me know and I'll resubmit. I'm getting this error regularly, especially when I'm using the app heavily. Nothing fixes it except resetting my phone. 

Exception: java.io.FileNotFoundException
/storage/0403-0201/Android/data/org.quantumbadger.redreader/cache/8d186ee5-5f18-4f9a-b459-29ba942f5510.rr_cache_data_tmp: open failed: EROFS (Read-only file system)
  libcore.io.IoBridge.open(IoBridge.java:452)
  java.io.FileOutputStream.<init>(FileOutputStream.java:87)
  java.io.FileOutputStream.<init>(FileOutputStream.java:72)
  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:222)
  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:209)
  org.quantumbadger.redreader.cache.CacheManager.openNewCacheFile(CacheManager.java:295)
  org.quantumbadger.redreader.cache.CacheDownload$2.onSuccess(CacheDownload.java:157)
  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:143)
  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:140)
  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:87)
  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)
Caused by: Exception: android.system.ErrnoException
open failed: EROFS (Read-only file system)
  libcore.io.Posix.open(Native Method)
  libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
  libcore.io.IoBridge.open(IoBridge.java:438)
  java.io.FileOutputStream.<init>(FileOutputStream.java:87)
  java.io.FileOutputStream.<init>(FileOutputStream.java:72)
  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:222)
  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:209)
  org.quantumbadger.redreader.cache.CacheManager.openNewCacheFile(CacheManager.java:295)
  org.quantumbadger.redreader.cache.CacheDownload$2.onSuccess(CacheDownload.java:157)
  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:143)
  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:140)
  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:87)
  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)

**Comment by QuantumBadger** [comment] 2018-09-11 18:14
Thanks for the report @agibson1083. How much free space do you have on your device? Do any other apps encounter issues if you try to download files?

**Comment by nims11** [comment] 2018-12-13 12:39
Any update on this? I ran into the same issue today. Clearing app's cache and data doesn't seem to fix the issue.

**Comment by powerfulparadox** [comment] 2019-06-16 17:13
I had a similar error a while back that I worked around by reinstalling. Now It resurfaced.
Exception: java.io.FileNotFoundException
/storage/emulated/0/Android/data/org.quantumbadger.redreader/cache/08f7190d-ce54-4533-b378-2eef76c1e4df.rr_cache_data_tmp (Permission denied)
  java.io.FileOutputStream.open(Native Method)
  java.io.FileOutputStream.<init>(FileOutputStream.java:221)
  java.io.FileOutputStream.<init>(FileOutputStream.java:169)
  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:222)
  org.quantumbadger.redreader.cache.CacheManager$WritableCacheFile.<init>(CacheManager.java:209)
  org.quantumbadger.redreader.cache.CacheManager.openNewCacheFile(CacheManager.java:295)
  org.quantumbadger.redreader.cache.CacheDownload$2.onSuccess(CacheDownload.java:157)
  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$2.executeInThisThread(OKHTTPBackend.java:185)
  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:140)
  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:87)
  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)

**Comment by eragon9896** [comment] 2020-09-27 00:26
Getting this error every time I try to save anything after uninstalling 1.14 and reinstalling 1.13. I have 16GBs free. Any help would be greatly appreciated, this is my favourite reddit app. 

Error report -- RedReader v1.13

Manufacturer: samsung
Model: SM-N960W
Product: crownqltecs
Android release: 10
Android SDK: 29

-------------------------------
Title: Unexpected Storage Error
Message: An unknown internal error has occurred, related to the cache storage. You are probably running out of space.
URL: https://i.redd.it/9f6sa58r4ip51.jpg
Exception: java.io.FileNotFoundException
/storage/emulated/0/Pictures/9f6sa58r4ip51.jpg: open failed: EACCES (Permission denied)
  libcore.io.IoBridge.open(IoBridge.java:496)
  java.io.FileOutputStream.<init>(FileOutputStream.java:235)
  java.io.FileOutputStream.<init>(FileOutputStream.java:186)
  org.quantumbadger.redreader.common.General.copyFile(General.java:135)
  org.quantumbadger.redreader.image.SaveImageCallback$1$1.onSuccess(SaveImageCallback.java:172)
  org.quantumbadger.redreader.cache.CacheRequest.notifySuccess(CacheRequest.java:313)
  org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread$1.run(CacheManager.java:542)
  org.quantumbadger.redreader.common.PrioritisedCachedThreadPool$Executor.run(PrioritisedCachedThreadPool.java:107)
  java.lang.Thread.run(Thread.java:919)
Caused by: Exception: android.system.ErrnoException
open failed: EACCES (Permission denied)
  libcore.io.Linux.open(Native Method)
  libcore.io.ForwardingOs.open(ForwardingOs.java:167)
  libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
  libcore.io.ForwardingOs.open(ForwardingOs.java:167)
  android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8002)
  libcore.io.IoBridge.open(IoBridge.java:482)
  java.io.FileOutputStream.<init>(FileOutputStream.java:235)
  java.io.FileOutputStream.<init>(FileOutputStream.java:186)
  org.quantumbadger.redreader.common.General.copyFile(General.java:135)
  org.quantumbadger.redreader.image.SaveImageCallback$1$1.onSuccess(SaveImageCallback.java:172)
  org.quantumbadger.redreader.cache.CacheRequest.notifySuccess(CacheRequest.java:313)
  org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread$1.run(CacheManager.java:542)
  org.quantumbadger.redreader.common.PrioritisedCachedThreadPool$Executor.run(PrioritisedCachedThreadPool.java:107)
  java.lang.Thread.run(Thread.java:919)

**Comment by QuantumBadger** [comment] 2020-09-27 09:46
@eragon9896 That error was fixed in v1.14, it happens because v1.13 uses APIs for saving images which are no longer supported.

**Comment by eragon9896** [comment] 2020-09-27 10:31
What an odd thing, 1.13 was still working just minutes before I updated this morning. I'm not a programmer so I don't know how any of it works. Unfortunate but what can ya do. Thank you for the answer and all your work :)

**Comment by QuantumBadger** [comment] 2021-06-13 12:40
I think this has been resolved with the SAF changes, and the FAT files-per-directory workaround.

**Closed by QuantumBadger** 2021-06-13 12:40 UTC
Labels: Bug
