### ISSUE TITLE
Permission Denied when viewing v.reddit links

### ISSUE THREAD

**Issue by sbaraka** [QuantumBadger/RedReader#756] opened 2020-07-08 15:49 UTC
Random permission denied errors when viewing random v.reddit links.

Anyone else running into this issue?

**Comment by QuantumBadger** [comment] 2020-07-08 15:53
Thanks for the report, but this is a duplicate of #752 and #753 which I fixed a week ago ;) If you update to v1.11 then this should be resolved.

**Closed by QuantumBadger** 2020-07-08 15:53 UTC
