### ISSUE TITLE
View messages you sent/received

### ISSUE THREAD

**Issue by ihailfromreddit** [QuantumBadger/RedReader#555] opened 2017-12-19 03:55 UTC
Is there a way to view messages you sent/received in a conversation similar to what you can see at:

https://www.reddit.com/message/messages/

A way to see sent and received messages in a conversation view

**Comment by ihailfromreddit** [comment] 2017-12-20 20:41
Sorry, this seems to be a duplicate of issue #443 (https://github.com/QuantumBadger/RedReader/issues/443)

**Comment by QuantumBadger** [comment] 2018-01-16 08:32
Closing as duplicate of #443 :)

**Closed by QuantumBadger** 2018-01-16 08:32 UTC
Labels: Duplicate
