### ISSUE TITLE
Text incorrectly shows up as: <emote: #* in tables in new Alpha 199

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#745] opened 2020-06-14 22:47 UTC
This happens in the new Alpha 199 with table support.

Example of code that does not render properly:
```
[](#sprite1-p12) **Borussia Dortmund:**
[](#sprite6-p167) Roman Bürki
```

That actually shows up in the app as:

<emote: #sprite1-p12> **Borussia Dortmund**
<emote: #sprite6-p167> Roman Bürki

from [this Reddit post](https://www.reddit.com/r/soccer/comments/gkuh6c/match_thread_borussia_dortmund_vs_schalke_04/)

**Comment by QuantumBadger** [comment] 2020-06-15 16:12
Thanks, should be fixed in Alpha 200 (commit https://github.com/QuantumBadger/RedReader/commit/a0d6a437500e31f435d7826464bb1477db438500).

It was intended behaviour to show emotes as `<emote: #name>`, which worked okay for subreddits where they were rare, but clearly not for /r/soccer where they absolutely spam posts with them :)

Emotes are now hidden (consistent with reddit itself), and we also now avoid showing them as links that don't go anywhere.

**Closed by QuantumBadger** 2020-06-15 16:12 UTC

**Comment by QuantumBadger** [comment] 2020-06-15 16:51
Issue #120 is related, for showing the emotes properly.
