### ISSUE TITLE
red reader crash

### ISSUE THREAD

**Issue by lesto** [QuantumBadger/RedReader#383] opened 2016-09-09 07:06 UTC
Today Evert time i open the front page red reader try to update the post list and crash. I can see the list appear for a moment before crashing

**Comment by QuantumBadger** [comment] 2016-09-09 07:22
Thanks for the report. This is caused by a breaking reddit API change :(

https://github.com/reddit/reddit/issues/1692

Fixed in Alpha 81 (available now), and v1.9.5.2 (on Google Play in a few hours, F-Droid within 24 hours).

**Closed by QuantumBadger** 2016-09-09 07:22 UTC

**Comment by lesto** [comment] 2016-09-09 21:56
It seems to be fixed even without update (still using old version 'cause fdroid)

**Comment by lesto** [comment] 2016-09-09 21:56
It seems to be fixed even without update (still using old version 'cause fdroid)

**Comment by QuantumBadger** [comment] 2016-09-10 07:26
> It seems to be fixed even without update (still using old version 'cause fdroid)

It depends on which posts are on the page you view -- if any of them have the new "thumbnail": "image" field, the old version will crash :(

**Comment by lesto** [comment] 2016-09-10 09:43
Yep, as soon as I reloaded the page I crashed. Thanks very much for RR and your fast release, now I'm waiting f-droid -.-"
