### ISSUE TITLE
Error: The server did not accept the request for an unknown reason. Please try again.

### ISSUE THREAD

**Issue by Rbagman** [QuantumBadger/RedReader#437] opened 2017-02-05 16:02 UTC
Have been using the Tor feature for months; this morning it stopped working.

Reboot corrected this.

https://oauth.reddit.com/hot/.json

Exception: java.io.IOException
unexpected end of stream on null
  com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
  com.squareup.okhttp.internal.io.RealConnection.createTunnel(RealConnection.java:270)
  com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:172)
  com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
  com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
  com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
  com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
  com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
  com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
  com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
  com.squareup.okhttp.Call.getResponse(Call.java:286)
  com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
  com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
  com.squareup.okhttp.Call.execute(Call.java:80)
  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:111)
  org.quantumbadger.redreader.reddit.api.RedditOAuth.fetchAccessTokenSynchronous(RedditOAuth.java:607)
  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:119)
  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:88)
  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)
Caused by: Exception: java.io.EOFException
\n not found: size=0 content=...
  okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
  com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
  com.squareup.okhttp.internal.io.RealConnection.createTunnel(RealConnection.java:270)
  com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:172)
  com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
  com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
  com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
  com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
  com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
  com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
  com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
  com.squareup.okhttp.Call.getResponse(Call.java:286)
  com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
  com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
  com.squareup.okhttp.Call.execute(Call.java:80)
  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:111)
  org.quantumbadger.redreader.reddit.api.RedditOAuth.fetchAccessTokenSynchronous(RedditOAuth.java:607)
  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:119)
  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:88)
  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)

**Comment by QuantumBadger** [comment] 2017-02-07 19:06
Thanks for the report. I think the problem was likely caused by a dodgy exit node, and rebooting caused a new Tor route to be chosen.

I'll close this issue for now, as I don't think there's an issue with the app, although please do let me know if you notice this again.

**Closed by QuantumBadger** 2017-02-07 19:06 UTC
