### ISSUE TITLE
Feature request: basic mod tools

### ISSUE THREAD

**Issue by jellie-bean** [QuantumBadger/RedReader#1080] opened 2023-06-27 08:44 UTC
Currently no mod tools in app.

**Comment by nascentt** [comment] 2023-07-01 23:28
Duplicate of https://github.com/QuantumBadger/RedReader/issues/641

**Comment by QuantumBadger** [comment] 2023-07-03 17:47
Thanks both, closing as a dupe. I'm hoping to add some initial mod tools soon.

**Closed by QuantumBadger** 2023-07-03 17:47 UTC
