### ISSUE TITLE
Feature Request: Multireddit editing

### ISSUE THREAD

**Issue by dylanrees** [QuantumBadger/RedReader#500] opened 2017-05-19 07:37 UTC
I use the multireddit feature a decent amount, and It'd be nice to be able to add and remove subs from multireddits from within the app.

**Comment by QuantumBadger** [comment] 2017-05-21 08:10
Thanks, agreed this would be useful.

Just checked and it looks like this is a duplicate of issue #15 :)

**Closed by QuantumBadger** 2017-05-21 08:10 UTC
