### ISSUE TITLE
Status 403 under TOR

### ISSUE THREAD

**Issue by moshpirit** [QuantumBadger/RedReader#290] opened 2016-03-28 20:34 UTC
Yesterday I became root on my phone so I torified all my apps, including RedReader Beta, often I get an error telling me that I'm not allowed to do whatever I'm doing. When I see the details, looks like it's [403](https://en.wikipedia.org/wiki/HTTP_403).

This is very weird because I've entered into Reddit tons of times on the desktop TOR browser and I never got this error.

**Comment by QuantumBadger** [comment] 2016-03-28 20:59
This could be because Tor is regularly changing your IP, and reddit's oAuth stuff requires you to stay on a single IP.

It might be possible to work around this by re-authenticating for every single request. You could test this by modifying the following line:

https://github.com/QuantumBadger/RedReader/blob/master/src/main/java/org/quantumbadger/redreader/cache/CacheDownload.java#L98

From:

    if(accessToken == null || accessToken.isExpired()) {

To:

    if(true) {

Please let me know if that works :)

**Comment by moshpirit** [comment] 2016-03-28 21:07
I'm not a developer, so I don't know how to create an APK with those changed lines :( 

Thanks for your quick answer!

**Comment by moshpirit** [comment] 2016-03-29 19:32
OK, I'm having some troubles with others apps and looks like forcing them to use TOR (individually) solve it. Maybe that would be a possible solution: adding a TOR support.

**Comment by QuantumBadger** [comment] 2016-04-03 20:03
More discussion of this over here: https://github.com/QuantumBadger/RedReader/issues/296

**Comment by QuantumBadger** [comment] 2016-04-05 20:36
Tor support is now merged in (see [alpha 21](https://redreader.org/alpha/)). The 403 errors are apparently still occurring though :(

**Comment by moshpirit** [comment] 2016-04-05 20:47
Hmm ,that's weird! I've been using Diode these days and I had no issue :\ (of course under TOR) 

Thanks for the update!

**Comment by SpotComms** [comment] 2016-06-26 15:58
So I did eventually figure out the 403 issue. Its nothing to do with RedReader. The Reddit API actively blocks access from Tor. An easy workaround is setting your exit node country in Orbot to Australia or New Zealand (Only countries I've found so far that work).

**Comment by moshpirit** [comment] 2016-06-26 16:01
This is not because of the exit node, but because of the amount of people that are connected using the same exit node

**Comment by SpotComms** [comment] 2016-06-26 16:07
Either way, this issue can be closed as nothing can be done code-wise in RedReader to fix it.

**Comment by moshpirit** [comment] 2016-06-26 16:09
But this is too weird. On TOR browser I don't have any issue, why should I have it with the API?

**Comment by QuantumBadger** [comment] 2016-07-08 17:47
I've sent the admins an email about this. I'll let you know if I hear back!

**Comment by itmike** [comment] 2016-07-14 22:37
I think this is because, like many other sites(eg. google), they require some extra "security" when they detect you are likly to use tor. Logging in with a 3rd party xmpp client to google over tor give you similar issues. :(

**Comment by QuantumBadger** [comment] 2016-08-06 22:49
I emailed reddit about this a month ago, but my email was ignored :(

I've opened up a ticket here: https://github.com/reddit/reddit/issues/1664

**Comment by moshpirit** [comment] 2016-08-06 22:51
Thank you!! :)

**Comment by QuantumBadger** [comment] 2016-08-07 15:40
@moshpirit (and others) -- can you reproduce this issue with Alpha 70? (https://redreader.org/alpha/)

**Comment by SpotComms** [comment] 2016-08-07 16:12
With 761f621ffadcde183a72d031845b0aa5690fde50 I did get a 403 after a few minutes.

**Comment by QuantumBadger** [comment] 2016-08-07 16:29
Thanks @SpotComms.

I've been asked for the details of a request/response when this occurs, but I've been trying to repro this for a whole hour and haven't been able to.

Would you mind please trying again with the "httplog" branch, which should log out the full contents of each HTTP connection to logcat:

https://github.com/QuantumBadger/RedReader/commit/09483c6a92ea5e6d61314a879333aba5cae62b4e

We can then post the relevant parts of the log on the reddit ticket:

https://github.com/reddit/reddit/issues/1664

**Comment by SpotComms** [comment] 2016-08-07 16:41
Wow, its Cloudflare throwing a captcha... give me a second I'll edit with log.

**Comment by QuantumBadger** [comment] 2016-08-07 16:58
Excellent, thank you! I guess that narrows it down a bit!!

I'll post a link to that log in the reddit ticket.

**Comment by SpotComms** [comment] 2016-08-07 18:08
So since Reddit users connecting via TOR are a minority and people have tried to get CloudFlare to stop blocking TOR users in the past and failed, the only solution to this will be showing the CF captcha in a webview or using a library like this [one](https://github.com/ayltai/Android-Lib-reCAPTCHA) if possible. And then sending the cookie along with future requests. The big issue with that is we don't know how quickly those tokens expire, so users might end up having to solve a captcha every few minutes. I'll give it a try later when I get a chance.

**Comment by QuantumBadger** [comment] 2016-08-08 19:26
@SpotComms The admins are asking for a CloudFlare ray ID of a connection where this occurred. I'm still not able to repro this myself at the moment -- are you able to provide the ray ID of the attached log (or repro it again and get the new ID?)

https://www.reddit.com/r/bugs/comments/4wre66/cloudflare_blocks_reddit_api_requests_from_tor/

**Comment by SpotComms** [comment] 2016-08-08 19:44
@QuantumBadger https://gist.github.com/SpotComms/7b82d080d44a24a61e705513d2ed116c

**Comment by QuantumBadger** [comment] 2016-08-08 19:54
@SpotComms Thanks, I've posted that link to the thread. I'll try those repro steps next time (I've been testing by viewing lots of different subs in succession rather than scrolling down).

**Comment by QuantumBadger** [comment] 2016-08-09 07:04
CloudFlare are asking for a fully unredacted connection log to be emailed to them:

https://www.reddit.com/r/bugs/comments/4wre66/cloudflare_blocks_reddit_api_requests_from_tor/d69vlz2

I'll try again to repro this when I get home tonight, but if anyone has any luck in the meantime please let me (and/or them) know :)

**Comment by QuantumBadger** [comment] 2016-08-09 17:03
Woohoo, I repro'ed it first try :)

**Comment by QuantumBadger** [comment] 2016-08-15 20:58
The admins say they've put in a fix for this, and want to know if the issue is still reproducible. I've been trying but haven't seen it again so far.

@SpotComms and @moshpirit -- please could you confirm that the issue is fixed for you?

**Comment by moshpirit** [comment] 2016-08-15 21:14
I've just enabled TOR again on Reddit, I'll let you know if I get the error again!! Thanks for the quick report!! :)

**Comment by SpotComms** [comment] 2016-08-15 21:22
Can confirm, I can't seem to hit a 403.

**Comment by QuantumBadger** [comment] 2016-08-16 06:57
Great, thanks! I'll close the issue for now.

**Closed by QuantumBadger** 2016-08-16 06:57 UTC
Labels: Bug

**Comment by moshpirit** [comment] 2016-08-16 08:26
Just posted it on /r/privacy so more people can relate that this is finally fixed ;)

**Comment by jeetsee** [comment] 2016-09-09 12:40
When I use this option and try to view my inbox or modmail I get an error saying "the user is not authorized for this action".   This is with 1.9.5.1.

If I use RedReader with OrBot transparent proxy it works ok.

**Comment by SpotComms** [comment] 2016-09-09 20:35
@jeetsee tbh I never tested any account related parts because I don't actually have a Reddit account.
