### ISSUE TITLE
Regression: lost ability to visit hidden subs

### ISSUE THREAD

**Issue by poelzi** [QuantumBadger/RedReader#1006] opened 2022-05-25 18:00 UTC
There was a way to visit a known sub by typing the name. The new search functionality does not allow you 
to visit a community that is not visible through search.

Maybe a button next to the search field that will go to the searched text as sub name might fix this, or the the old menu item back.

**Comment by QuantumBadger** [comment] 2022-06-02 12:08
Closing as dupe of #994.

**Closed by QuantumBadger** 2022-06-02 12:08 UTC
