### ISSUE TITLE
An option to hide post/comment scores

### ISSUE THREAD

**Issue by suhr** [QuantumBadger/RedReader#689] opened 2019-11-02 11:14 UTC
Scores are nice for sorting but they affect your opinion about a post before you read it. Thus it would be nice to have an option to display posts and comments without scores.

**Comment by KelianB-IMTA** [comment] 2019-12-02 10:03
Should we also default to sorting by new instead of best when enabling this? Otherwise you will still be influenced since you know the first posts / comments are the most upvoted.

**Comment by suhr** [comment] 2019-12-02 10:35
No, let default sorting to be a separate option.

**Comment by neilweber** [comment] 2020-01-10 22:52
Duplicate of #669.

**Closed** 2020-02-22 10:37 UTC
