### ISSUE TITLE
Closing bracket is not considered part of a link

### ISSUE THREAD

**Issue by airon90** [QuantumBadger/RedReader#392] opened 2016-09-21 13:28 UTC
See screenshot
![screenshot_2016-09-16-16-14-17](https://cloud.githubusercontent.com/assets/139841/18712737/0751e468-8010-11e6-9107-f6b658678b43.png)

**Comment by jimmyklein4** [comment] 2017-01-07 00:54
I don't know if this has already been fixed, but if I'm not mistaken this is working as intended. I tried this both with and without the escape character and it behaves exactly as it does on the site. Putting an escape character before the parentheses will make the link work

**Comment by QuantumBadger** [comment] 2017-01-08 18:27
> behaves exactly as it does on the site

That's what I thought as well, but I've found that specific comment on the site, and it looks like the bracket is included in the link:

https://www.reddit.com/r/italy/comments/531abl/fiocco_rosa_per_giorgia_meloni_%C3%A8_nata_ginevra/d7p78d3/

**Comment by QuantumBadger** [comment] 2017-07-11 19:24
It looks like reddit treats a closing bracket as part of the link if:

* There is an opening bracket somewhere before it in the link, e.g. `https://www.google.com(abc)`
* There is more link text after the bracket, e.g. `https://www.google.com)abc`

**Comment by QuantumBadger** [comment] 2017-07-11 19:37
Fixed :)

**Closed** 2017-07-11 19:37 UTC
Labels: Bug
