### ISSUE TITLE
Permission Denied Errors virwing v.Reddit links

### ISSUE THREAD

**Issue by streetraider** [QuantumBadger/RedReader#753] opened 2020-07-03 15:28 UTC
On version 1.10 different v.reddit links are giving me a permission denied error. Not all v.reddit links are throwing the error, but a majority of them are. 

Specific link I'm getting the error: https://v.redd.it/i6pnfsdhtm851/DASH_720.mp4?source=fallback

**Comment by joaofauvel** [comment] 2020-07-03 16:42
Same here. The v.reddit works on external app.

**Comment by nullzel** [comment] 2020-07-03 18:11
Came here to post this. Please fix, I love your open source Reddit reader.

**Comment by QuantumBadger** [comment] 2020-07-03 19:01
Thanks for the report guys, but this is a duplicate of #752 :)

I fixed it and uploaded the update two days ago, but I'm waiting for Google's app approval process.

**Closed by QuantumBadger** 2020-07-03 19:01 UTC

**Comment by QuantumBadger** [comment] 2020-07-03 19:07
If anyone wants the update sooner, it's available here:

https://github.com/QuantumBadger/RedReader/releases/tag/v1.11
