### ISSUE TITLE
Unable to connect to oauth.reddit.com

### ISSUE THREAD

**Issue by 4ut0-M-4t** [QuantumBadger/RedReader#597] opened 2018-05-23 19:51 UTC
Android version: 6.0.1
RedReader version: 1.9.8.5 (F-droid)

Steps to reproduce:
1. Start the app. Do not log in.
2. Configure TOR proxy.
3. Navigate to *Custom Location*.
4. Attempt to visit any subreddit.
The error message is as follows:
=The server did not accept the request for an unknown reason.=

I can post the full contents of the error message, if need be.

**Comment by QuantumBadger** [comment] 2018-05-25 06:40
Thanks for the report -- I assume this only occurs on Tor?

This looks quite similar to #437, and is likely to be either a dodgy exit node, or reddit rejecting the request. The full error log (including HTTP error code) may be helpful.

**Comment by 4ut0-M-4t** [comment] 2018-06-01 22:09
Sorry. I usually look through all open and closed issues before posting. Missed that one somehow. 
Though I didn't try to configure TOR connection in the app's settings, just using a net proxy. Changing an exit node didn't fix this. 

Full error log: 
`Exception: java.net.ConnectException
Failed to connect to www.reddit.com/127.0.0.1:443
  okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
  okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
  okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
  okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
  okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
  okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
  okhttp3.RealCall.execute(RealCall.java:77)
  org.quantumbadger.redreader.http.okhttp.OKHTTPBackend$1.executeInThisThread(OKHTTPBackend.java:117)
  org.quantumbadger.redreader.reddit.api.RedditOAuth.fetchAnonymousAccessTokenSynchronous(RedditOAuth.java:681)
  org.quantumbadger.redreader.cache.CacheDownload.performDownload(CacheDownload.java:115)
  org.quantumbadger.redreader.cache.CacheDownload.doDownload(CacheDownload.java:87)
  org.quantumbadger.redreader.cache.CacheDownloadThread.run(CacheDownloadThread.java:36)
Caused by: Exception: java.net.ConnectException
failed to connect to www.reddit.com/127.0.0.1 (port 443) after 15000000ms: isConnected failed: ECONNREFUSED (Connection refused)
  libcore.io.IoBridge.isConnected(IoBridge.java:234)
  libcore.io.IoBridge.connectErrno(IoBridge.java:171)
  libcore.io.IoBridge.connect(IoBridge.java:122)` 

I will check VPN connection ASAP.

**Comment by QuantumBadger** [comment] 2018-06-02 07:11
From that error log:

`Failed to connect to www.reddit.com/127.0.0.1:443`

It seems like your DNS server is giving the IP `127.0.0.1` (i.e. your local device's IP) for `www.reddit.com`, which is obviously wrong :) Which DNS server are you using?

**Comment by 4ut0-M-4t** [comment] 2018-06-05 14:57
Generally I use OpenNIC's anycast address: **185.121.177.177** in the router's settings. But TOR uses its own.

I've tried configuring TOR connection in the app's *Network* settings + Orbot VPN settings and now there's no connection issue.

**Comment by QuantumBadger** [comment] 2018-06-24 08:58
Thanks, closing ticket as it sounds like the issue is gone.

**Closed by QuantumBadger** 2018-06-24 08:58 UTC

**Comment by 4ut0-M-4t** [comment] 2018-09-13 01:40
_To anyone suffering from a similar issue_:
Mine was actually caused by a particular hosts file source. I'm using AdAway with StevenBlack's consolidated ads&fakenews&**social** blocking list as I strive to avoid major social networks (reddit being one of a couple exceptions).
@QuantumBadger, thank you for your excellent app and dedication to bug hunting, but this was entirely my fault. I should've checked hosts after I'd seen redirects to 127.0.0.1 for any network connection type other than Orbot's (obviously ignoring local address resolving).
