### ISSUE TITLE
No Way To Reply To Inbox Messages

### ISSUE THREAD

**Issue by nikfrei** [QuantumBadger/RedReader#278] opened 2016-02-25 21:36 UTC
Clicking, double clicking and long clicking on a PM in inbox does nothing.

Also there are no ways to check sent messages, nor possible to send messages to a username.

**Comment by QuantumBadger** [comment] 2016-04-03 20:13
Duplicate of https://github.com/QuantumBadger/RedReader/issues/259, but this has more detail, so I'll close the other one :)

**Comment by QuantumBadger** [comment] 2016-07-09 09:56
Added ability to send PMs to username, and reply to inbox messages.

I'll open a new issue to cover the list of sent messages.

**Closed by QuantumBadger** 2016-07-09 09:56 UTC
Labels: Enhancement
