### ISSUE TITLE
Stream and Download/Share videos from m3u8 file

### ISSUE THREAD

**Issue by vdurante** [QuantumBadger/RedReader#729] opened 2020-04-22 21:01 UTC
I have never developed Java/Android, but as I was reading through the source code and I noticed RedReader merges Dash + Audio to display videos. This works on the app's video player, but fails when downloading/sharing the video elsewhere. I've also seen other users have requested stream capabilities for the video player, since the current merge solution requires the video and audio to be downloaded beforehand.

At this point, RedReader downloads a DASH Playlist (ex https://v.redd.it/qakawehf50s41/DASHPlaylist.mpd) which describes the existing medias for such video. Then, both video (ex https://v.redd.it/qakawehf50s41/DASH_720) and audio (ex https://v.redd.it/qakawehf50s41/audio) are picked, downloaded and merged. What I propose is to use the streaming alternative (`HLS Playlist`) for `v.reddit` videos (ex https://v.redd.it/qakawehf50s41/HLSPlaylist.m3u8).

1. Saving, Downloading, Sharing -> for easy implementation, I would suggest using something like ffmpeg, which handles such files perfectly. Through command line, I am able to download the file using `ffmpeg -i https://v.redd.it/qakawehf50s41/HLSPlaylist.m3u8 test.mp4`. A few references: [FFMPEG for Android](https://github.com/tanersener/mobile-ffmpeg), [FFMPEG Java CLI Wrapper](https://github.com/bramp/ffmpeg-cli-wrapper)
2. Visualizing -> I read on the source code a few mentions to VLC, although I am unsure if it is used to display the videos. I found the java class file that displays the video, but couldn't recognize if it uses VLC. HLS is supported by major media players. I am unsure if the same happens on Android.

I honestly feel like such changes wouldn't be so complex, specially on (1). Implementing (2) could be a hassle if the media player doesn't support HLS.

**Comment by QuantumBadger** [comment] 2020-07-15 21:44
Thanks for the info!

Currently we use ExoPlayer for rendering videos -- the references to VLC are for a preference which allows users to open videos in the external VLC app.

A lot of stuff in RR is made more complicated by the fact that we use the cache manager to download everything. I think if we were to extend the cache manager to expose an `InputStream` during the download, the existing DASH approach would work fine.

I'm very eager to avoid bringing FFMPEG (or any native libraries at all) into the app, mostly for security reasons. To mux the streams together for saving/sharing, we'd probably want to use Android's `MediaMuxer` class, as discussed in #532.

For now I'll close this ticket as a dupe of #532 and #659, but if there's a compelling reason to switch to m3u8 that I've missed please let me know.

**Closed by QuantumBadger** 2020-07-15 21:44 UTC
